config/routes.rb
Rails.application.routes.draw do
  resources :calendars

	root 'application#index'

	devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

	resources :sermons
	get '/change_sermon' => 'sermons#change_sermon'
	get '/sermon_audio' => 'sermons#audio'

	#get '/calendar' => 'application#calendar'
	resources :calendars, except: [:show, :create, :new]
	get '/calendar/:id/download' => 'calendars#download'

	get '/dashboard' => 'admin#dashboard'
	get '/dashboard/koinonia' => 'admin#koinonia'
	get '/dashboard/calendars' => 'admin#calendars'
	get '/dashboard/sermons' => 'admin#sermons'
	get '/dashboard/alert' => 'admin#alert'
	post '/dashboard/update_alert' => 'admin#update_alert'

	resources :koinonia, except: [:show]
	get '/koinonia/download/:id' => 'koinonia#download'

	get '/ministries' => 'ministries#index'
	get '/prayer' => 'ministries#prayer_index'
	post '/prayer_request' => 'ministries#send_request'

	get '/download_jan' => 'application#download_jan'
	get '/download_feb' => 'application#download_feb'

	get '/contact' => 'application#contact'
end

app/views/admin/alert.html.erb
<%= content_for :dash do %>
	<h1>Alert</h1>

	

	<%= form_tag "/dashboard/update_alert", id: 'alert-form', remote: true do %>
		<label class="label-switch">
			<%= check_box_tag "active", 1, @alert.active %>
			<div class="checkbox"></div>
		</label><br>

		<%= text_field_tag :name, @alert.name, placeholder: 'Alert Title', disabled: @alert.active %><br>
		<%= text_area_tag :description, @alert.description, placeholder: 'Alert Text', disabled: @alert.active %>
	<% end %>
<% end %>

app/views/admin/calendars.html.erb
<%= content_for :dash do %>
	<h1>Calendars</h1>

	<table width="100%" id="manage-calendars">
		<tr>
			<th>Month</th>
			<th>Current File</th>
			<th>Last Updated</th>
			<th>Upload New</th>
		</tr>
		<% @calendars.each do |c| %>
			<tr id="<%= c.id %>">
				<td><b><%= c.name %><b></td>
				<td><%= link_to c.pdf, c.pdf_url %></td>
				<td><%= c.updated_at.in_time_zone("America/Denver").strftime("%m-%d-%Y") %></td>
				<td><%= link_to 'Upload New', edit_calendar_path(c), remote: true %></td>
			</tr>
		<% end %>
	</table>


<% end %>

app/views/admin/dashboard.html.erb
<%= content_for :dash do %>
	<h1>Analytics</h1>

	<div id="embed-api-auth-container"></div>
	<div id="chart-container"></div>
	<div id="view-selector-container"></div>

	<script>
		(function(w,d,s,g,js,fs){
		g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
		js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
		js.src='https://apis.google.com/js/platform.js';
		fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
		}(window,document,'script'));
	</script>

	<script>

		gapi.analytics.ready(function() {

		/**
		* Authorize the user immediately if the user has already granted access.
		* If no access has been created, render an authorize button inside the
		* element with the ID "embed-api-auth-container".
		*/
		gapi.analytics.auth.authorize({
		container: 'embed-api-auth-container',
		clientid: '597742318472-8iqs18hqdk49b0hf849ogaiqhkugv2ik.apps.googleusercontent.com',
		});


		/**
		* Create a new ViewSelector instance to be rendered inside of an
		* element with the id "view-selector-container".
		*/
		var viewSelector = new gapi.analytics.ViewSelector({
		container: 'view-selector-container'
		});

		// Render the view selector to the page.
		viewSelector.execute();


		/**
		* Create a new DataChart instance with the given query parameters
		* and Google chart options. It will be rendered inside an element
		* with the id "chart-container".
		*/
		var dataChart = new gapi.analytics.googleCharts.DataChart({
		query: {
		  metrics: 'ga:sessions',
		  dimensions: 'ga:date',
		  'start-date': '30daysAgo',
		  'end-date': 'yesterday'
		},
		chart: {
		  container: 'chart-container',
		  type: 'LINE',
		  options: {
		    width: '100%'
		  }
		}
		});


		/**
		* Render the dataChart on the page whenever a new view is selected.
		*/
		viewSelector.on('change', function(ids) {
		dataChart.set({query: {ids: ids}}).execute();
		});

		});
		</script>
<% end %>

app/views/admin/koinonia.html.erb
<%= content_for :dash do %>
	<h1>Koinonia</h1>
	<%= link_to raw('<i class="fa fa-plus-circle"></i> Create New'), "/koinonia/new", id: 'new-koinonia-link', remote: :true %>
	<div id="new-koinonia"></div>

	<div id="k-entries">
	<% @koinonia.each do |k| %>
		<div class="k-entry" id="<%= k.id %>">
			<div class="k-entry-image"><%= image_tag k.image, width: '120px' %></div>
			<div class="k-entry-destroy"><%= link_to 'Delete', k, method: :delete, data: { confirm: 'Are you sure?' } %></div>
			<div class="k-entry-edit"><%= link_to 'Edit', edit_koinonium_path(k), remote: true %></div>
			<div class="k-entry-name"><%= k.name %></div>
			<div class="float-clear"></div>
		</div>
	<% end %>
	</div>
<% end %>

app/views/admin/sermons.html.erb
<%= content_for :dash do %>
	<h1>Sermon Aduio</h1>
	<%= link_to raw('<i class="fa fa-plus-circle"></i> Create New'), "/sermons/new", id: 'new-sermon-link', remote: :true %>
	<div id="new-sermon"></div>

	<div id="s-entries">
	<% @sermons.each do |s| %>
		<div class="k-entry" id="<%= s.id %>">
			<div class="k-entry-image"><%= image_tag s.image, width: '120px' %></div>
			<div class="k-entry-destroy"><%= link_to 'Delete', s, method: :delete, data: { confirm: 'Are you sure?' } %></div>
			<div class="k-entry-edit"><%= link_to 'Edit', edit_sermon_path(s), remote: true %></div>
			<div class="k-entry-name"><%= s.name %></div>
			<div class="float-clear"></div>
		</div>
	<% end %>
	</div>
<% end %>

app/views/admin/update_alert.js.erb
$("#alert-form #name").attr("disabled", <%= @alert.active %>);
$("#alert-form #description").attr("disabled", <%= @alert.active %>);