config/routes.rb
Rails.application.routes.draw do
  resources :calendars

	root 'application#index'

	devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

	resources :sermons
	get '/change_sermon' => 'sermons#change_sermon'
	get '/sermon_audio' => 'sermons#audio'

	#get '/calendar' => 'application#calendar'
	resources :calendars, except: [:show, :create, :new]
	get '/calendar/:id/download' => 'calendars#download'

	get '/dashboard' => 'admin#dashboard'
	get '/dashboard/koinonia' => 'admin#koinonia'
	get '/dashboard/calendars' => 'admin#calendars'
	get '/dashboard/sermons' => 'admin#sermons'
	get '/dashboard/alert' => 'admin#alert'
	post '/dashboard/update_alert' => 'admin#update_alert'

	resources :koinonia, except: [:show]
	get '/koinonia/download/:id' => 'koinonia#download'

	get '/ministries' => 'ministries#index'
	get '/prayer' => 'ministries#prayer_index'
	post '/prayer_request' => 'ministries#send_request'

	get '/download_jan' => 'application#download_jan'
	get '/download_feb' => 'application#download_feb'

	get '/contact' => 'application#contact'
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
	def audio_url
 		"public/sermons/#{self.id}.mp3"
 	end

 	def image_url
 		"public/sermons/#{self.id}.jpg"
 	end

 	def image
 		"/sermons/#{self.id}.jpg"
 	end

 	def audio
 		"/sermons/#{self.id}.mp3"
 	end
end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController
	before_action :set_sermon, only: [:show, :edit, :update, :destroy]

	# GET /sermons
	# GET /sermons.json
	def index
		playlist = Yt::Playlist.new id: 'PLZLN8ggsIxePmqamBkTYJEYHY-3sgenkQ'

		10.times do |x|
			begin
				all = playlist.playlist_items.map {|pi| pi}[0..20]
				@sermons = all.select {|s| s.public? }[0..3]
				
				# .where(privacy_status: 'public').map {|pi| pi}[0..20]
				break
			rescue
				if x == 9
					throw 'could not get videos'
				end
			end
		end
		
		@image = @sermons.first.snippet.data["thumbnails"]["high"]["url"]
		@image = Base64.encode64(open(@image).read)
	end

	def change_sermon
		@sermon = Yt::Video.new id: params[:id]
		@image = @sermon.snippet.data["thumbnails"]["high"]["url"]
		@image = Base64.encode64(open(@image).read)
		@player = @sermon.embed_html.html_safe
		@id = params[:id]
	end

	# GET /sermons/1
	# GET /sermons/1.json
	def show
		@sermon = VIDEO_CLIENT.my_video params[:id]
		@image = @sermon.thumbnails[3].url
		@image = Base64.encode64(open(@image).read)
		@player = @sermons[0].embed_html5({
			:class => 'video-player', :id => 'my-video',
			:width => '560',
			:height => '315',
			:frameborder => '0', 
			:controlls => '0',
			fullscreen: true
		}).html_safe
	end

	# GET /sermons/new
	def new
		@sermon = Sermon.new
	end

	# GET /sermons/1/edit
	def edit
		# @sermon = Sermon.find params[:id]
		render 'new.js.erb'
	end


	def audio
		@sermons = Sermon.all[0..11].reverse
	end



	# POST /sermons
	# POST /sermons.json
	def create
		
		@sermon = Sermon.create name: params[:sermon][:name], sermondate: params[:sermon][:sermondate]

		if params[:files]
			audio = params[:files].find {|f| f.original_filename =~ /.mp3/}
			image = params[:files].find {|f| f.original_filename =~ /(.png|.jpg)/}
		end

		if audio
			File.open(@sermon.audio_url, "wb") do |file|
				file.write audio.read
			end
		end

		if image
			File.open(@sermon.image_url, "wb") do |file|
				file.write image.read
			end
		end
	end

	# PATCH/PUT /sermons/1
	# PATCH/PUT /sermons/1.json
	def update
		@sermon.update name: params[:sermon][:name], sermondate: params[:sermon][:sermondate]

		if params[:files]
			audio = params[:files].find {|f| f.original_filename =~ /.mp3/}
			image = params[:files].find {|f| f.original_filename =~ /(.png|.jpg)/}
		end

		if audio
			File.open(@sermon.audio_url, "wb") do |file|
				file.write audio.read
			end
		end

		if image
			File.open(@sermon.image_url, "wb") do |file|
				file.write image.read
			end
		end
	end

	# DELETE /sermons/1
	# DELETE /sermons/1.json
	def destroy
		@sermon = Sermon.find params[:id]

		if File.exists?(@sermon.image_url)
			File.delete(@sermon.image_url)
		end

		if File.exists?(@sermon.audio_url)
			File.delete(@sermon.audio_url)
		end

		@sermon.delete

		redirect_to "/dashboard/sermons"
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_sermon
			@sermon = Sermon.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def sermon_params
			params[:sermon]
		end
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/sermons/_entry.html.erb
<div class="k-entry" id="<%= @sermon.id %>">
	<div class="k-entry-image"><%= image_tag @sermon.image, width: '120px' %></div>
	<div class="k-entry-destroy"><%= link_to 'Delete', @sermon, method: :delete, data: { confirm: 'Are you sure?' } %></div>
	<div class="k-entry-edit"><%= link_to 'Edit', edit_sermon_path(@sermon), remote: true %></div>
	<div class="k-entry-name"><%= @sermon.name %></div>
	<div class="float-clear"></div>
</div>

app/views/sermons/_form.html.erb
<div id="sermon-form">
	<%= form_for @sermon, multipart: true, remote: true do |f| %>
		<h1>
			<%= @sermon.id == nil ? "New Sermon" : @sermon.name %>
		</h1>

		<%= f.text_field :name, placeholder: 'Name' %><br>
		<%= f.text_field :sermondate, placeholder: 'Sermon Date' %><br>
		
		<div id="select-sermon">Select Audio <span>None Selected</span></div>
		<div id="select-cover">Select Image <span>None Selected</span></div>

		<input type="file" name="files[]" id="sermon_files" multiple/>
		<%= f.file_field :image %>
		<%= f.file_field :audio %>

		<div id="s-<%= @sermon.id == nil ? 'create' : 'edit' %>"><%= @sermon.id == nil ? "Create" : "Save" %></div>
		
	<% end %>

	<div id="progress">
		<div class="bar-bg"></div>
		<div class="bar" style="width: 0%;"></div>
	</div>
</div>

app/views/sermons/audio.html.erb
<section id="sermonaudio">
	<audio id="audiosource" controls="controls">
		<source src="<%= @sermons.first.audio %>" type="audio/mpeg" />
		Your browser does not support the audio element.
	</audio>

	<div id="sermon-player">
		<h3><%= @sermons.first.name %></h3>
		<div class="container">
			<div class="column-2">
				<button onclick="toggleplayer()" id="control-button"><i class="fa fa-play"></i></button>
			</div>

			<div class="column-8" id="scrub">
				<div id="slider"></div>
			</div>

			<div id="sermon-time" class="column-2">
				<span id="current-time">0:00</span> / <span id="duration"></span>
			</div>	
		</div>
	</div>

	<div id="previous-audio">
		Sermon Listing<br>
		<i class="fa fa-angle-down"></i>
	</div>

	<div id="audio-list">
		<div class="container">
			<% @sermons.each do |s| %>
				<div class="audio-listing" name="<%= s.name %>" image="<%= s.image %>" audio="<%= s.audio %>">
					<div class="top-color"></div>
					<div class="sermon-thumb">
						<%= image_tag s.image %>
					</div>
					<div class="sermon-title"><h4><%= s.name %></h4></div>
					<div class="sermon-date"><%= s.sermondate %></div>
					<div class="float-clear"></div>
				</div>
			<% end %>
		</div>
	</div>


	<%= image_tag @sermons.first.image, id: "s-bg-image", width: "300px", height: '300px', onload: "initblur()" %>
	<canvas id="sermon-canvas" width="300px" height="300px"></canvas>
</section>



<script>
	var player, control, marker, updateplayer;
	var scrub = $("#slider");


	function toggleplayer() {
		if (player.paused) {
			player.play();
			control.removeClass('fa-play').addClass('fa-pause');
		} else {
			player.pause();
			control.removeClass('fa-pause').addClass('fa-play');
		}
	}


	function easytime(time) {
		minutes = Math.floor(time/60);
		seconds = Math.floor(time-(minutes*60));
		
		if (seconds < 10)
			seconds = "0" + seconds

		return minutes + ":" + seconds
	}


	function reset() {
		if (!player.paused) {
			toggleplayer();
		}
		player.currentTime = 0;
		$("#current-time").html(easytime(0));
		scrub.slider("option", "value", 0);
	}


	$(document).ready(function() {
		scrub.slider({
			step: 0.1
		});

		player = $("#audiosource")[0];
		control = $("#control-button i");
		marker = $("#current-marker");

		player.onended = function() {
			reset();
		}

		player.onloadedmetadata = function() {
			$("#duration").html(easytime(player.duration));
		};

		player.autostart = false;

		updateplayer = setInterval(function() {
			if (!player.paused) {
				current = player.currentTime;

				// Update Slider
				pos = (current * 100 / player.duration);
				//marker.css('margin-left', pos + '%').css('margin-left', '-=8px');
				scrub.slider("option", "value", pos);

				// Update Time
				$("#current-time").html(easytime(current));
			}
		}, 1000);


		scrub.on("slidestart", function(event, ui) {
			if (!player.paused) {toggleplayer();}
			
			player.pause();
		});

		scrub.on( "slidestop", function( event, ui ) {
			var current = player.duration * scrub.slider("option", "value") / 100;
			console.log(current);
			player.currentTime = current;
			$("#current-time").html(easytime(current));
			toggleplayer();
			player.play();
		} );

		scrub.on( "slide", function( event, ui ) {
			var current = player.duration * scrub.slider("option", "value") / 100;
			$("#current-time").html(easytime(current));
		});
	});
</script>

app/views/sermons/change_sermon.js.erb
// Fix Video Wrapper Height
var h = $("#semon-bg").height();
$("#sermon-bg").height(h);

// Remove Current Sermon
$('#current-sermon').fadeOut('slow');
$('#current-sermon').remove();

// Change src of image element
$("#s-bg-image").attr("src", "data:image/jpeg;base64,<%=j @image %>");

// Replace Video
var player = $("<%=j @player %>");
var sermon = $("<div id='current-sermon'></div>").hide();
sermon.append(player);
$("#current-sermon-wrap").append(sermon);
$("#current-sermon").fadeIn('slow');

// Change Title
$("#current-sermon-name").html("<b>Now Playing:</b> <%=j @sermon.title %>");

// Restore Height
$("#sermon-bg").height("auto");

app/views/sermons/create.js.erb
$("#sermon-form").fadeOut();
$("#screen").fadeOut();

var content = $("<%=j render 'entry', locals: {sermon: @sermon} %>").hide();
$("#s-entries").prepend(content);
content.fadeIn('slow');

app/views/sermons/edit.html.erb
<h1>Editing sermon</h1>

<%= render 'form' %>

<%= link_to 'Show', @sermon %> |
<%= link_to 'Back', sermons_path %>

app/views/sermons/index.html.erb
<div id="sermon-screen"></div>

<div id="sermon-bg">
	<div id="current-sermon-wrap">
		<div id="current-sermon">
			<%= @sermons[0].video.embed_html.html_safe %>
		</div>
	</div>
</div>

<div id="current-sermon-name">
	<b>Now Playing:</b> <%= @sermons[0].video.title %>
</div>

<div id="sermon-list">

	<div class="container">
		<% @sermons.each_with_index do |s| %>
			<div class="sermon-listing" id="<%= s.video_id %>">
				<div class="top-color"><%= image_tag s.thumbnail_url %></div>
				<div class="sermon-thumb">
					<%= image_tag s.thumbnail_url %>
				</div>
				<div class="sermon-title"><h4><%= s.title %></h4></div>
				<div class="float-clear"></div>
			</div>
		<% end %>
	</div>

</div>


<%= image_tag "data:image/jpeg;base64,#{@image}", id: "s-bg-image", width: "800px", height: '800px', onload: "initblur()" %>
<canvas id="sermon-canvas" width="800px" height="800px">
</canvas>

app/views/sermons/new.js.erb
var content = $("<%=j render 'form', locals: {sermon: @sermon} %>").hide();
$('body').append(content);
$('body').append('<div id="screen"></div>');
content.fadeIn();



var filelist = [];
audio_index = null;
image_index = null;


$('.new_sermon').fileupload({
	dataType: 'script',
	autoupload: false,
	singleFileUploads: false,

	add: function(e, data) {
		if (e.currentTarget.id == "sermon_audio") {

			// Get name and type of the file
			name = data.files[0].name;
			type = name.split(".").pop();

			// Validate file type
			if (type != "mp3")
				alert("Must be a mp3");
			else {
				// Indicate which file is selected
				$('#select-sermon span').html(name);

				// Determine indicies in filelist array
				if (audio_index == null) {
					audio_index = 0;
					image_index = 1;
				}

				// Add the file to filelist
				filelist[audio_index] = data.files[0];
			}

		}
		else if (e.currentTarget.id == "sermon_image") {
			
			// Get name of the file
			name = data.files[0].name;
			type = name.split(".").pop();

			// Validate file type
			if (type != "jpg" && type != "png")
				alert("Must be a jpg or png");
			else {
				// Indicate which file is selected
				$('#select-cover span').html(name);

				// Determine indicies in filelist array
				if (audio_index == null) {
					audio_index = 1;
					image_index = 0;
				}

				// Add the file to filelist
				filelist[image_index] = data.files[0];
			}
		}


	},

	progressall: function (e, data) {
		var progress = parseInt(data.loaded / data.total * 100, 10);
		$('#progress .bar').css(
			'width',
			progress + '%'
		);
	}
});

app/views/sermons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sermon_path(@sermon) %> |
<%= link_to 'Back', sermons_path %>

app/views/sermons/update.js.erb
$("#sermon-form").fadeOut();
$("#screen").fadeOut();
console.log("updated");

var entry = $("#<%= @sermon.id %>");
var content = $("<%=j render 'entry', locals: {sermon: @sermon} %>");
entry.replaceWith(content);