config/routes.rb
Rails.application.routes.draw do
  resources :calendars

	root 'application#index'

	devise_for :admins, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

	resources :sermons
	get '/change_sermon' => 'sermons#change_sermon'
	get '/sermon_audio' => 'sermons#audio'

	#get '/calendar' => 'application#calendar'
	resources :calendars, except: [:show, :create, :new]
	get '/calendar/:id/download' => 'calendars#download'

	get '/dashboard' => 'admin#dashboard'
	get '/dashboard/koinonia' => 'admin#koinonia'
	get '/dashboard/calendars' => 'admin#calendars'
	get '/dashboard/sermons' => 'admin#sermons'
	get '/dashboard/alert' => 'admin#alert'
	post '/dashboard/update_alert' => 'admin#update_alert'

	resources :koinonia, except: [:show]
	get '/koinonia/download/:id' => 'koinonia#download'

	get '/ministries' => 'ministries#index'
	get '/prayer' => 'ministries#prayer_index'
	post '/prayer_request' => 'ministries#send_request'

	get '/download_jan' => 'application#download_jan'
	get '/download_feb' => 'application#download_feb'

	get '/contact' => 'application#contact'
end

app/views/layouts/_links.html.erb
<ul>
	<!--<li><%= link_to 'Sermons', 'https://www.youtube.com/playlist?list=PLZLN8ggsIxePmqamBkTYJEYHY-3sgenkQ' %></li>-->
	<li><%= link_to 'Sermons', '/sermons' %></li>
	<!-- <li><%= link_to 'Ministries', '/ministries' %></li> -->
	<li><%= link_to "Ministerio Hispano", "https://ibdnabq.org" %><li>
	<li><%= link_to 'Blog', '/blog' %>
	<!-- <li><%= link_to 'Calendar', '/calendars' %></li> -->
	<li><%= link_to 'Koinonia', '/koinonia' %></li>
	<li><%= link_to 'Contact', '/contact' %></li>
	<li><%= link_to 'Give', 'https://onrealm.org/DelNorteBaptist/give/now', target: '_blank' %></li>
	<% if admin_signed_in? %>
		<li><%= link_to 'Admin', '/dashboard' %></li>
	<% end %>
	<!-- <li><%= link_to 'VBS', 'https://kideventpro.lifeway.com/myEvent/?id=64703' %> -->
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Del Norte Baptist Church</title>
	<meta name="description" content="We are a united body of believers committed to growing in Christ and reaching others for Christ.">

	<!-- Facebook Meta Tags -->
	<meta property="og:url" content="https://dnbc.org">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Del Norte Baptist Church">
	<meta property="og:description" content="We are a united body of believers committed to growing in Christ and reaching others for Christ.">
	<meta property="og:image" content="https://dnbc.org/og1.jpg">

	<!-- Twitter Meta Tags -->
	<meta name="twitter:card" content="summary_large_image">
	<meta property="twitter:domain" content="">
	<meta property="twitter:url" content="https://dnbc.org">
	<meta name="twitter:title" content="Del Norte Baptist Church">
	<meta name="twitter:description" content="We are a united body of believers committed to growing in Christ and reaching others for Christ.">
	<meta name="twitter:image" content="https://dnbc.org/og1.jpg">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto:100,300' rel='stylesheet' type='text/css'>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
	<%# <meta property="og:image" content="https://dnbc.org/og1.jpg" />
	<meta property="og:description" content="We are a united body of believers committed to growing in Christ and reaching others for Christ." />
	<meta property="og:url" content="http://dnbc.org" />
	<meta property="og:type" content="website" /> %>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-58403652-1', 'auto');
		ga('send', 'pageview');
	</script>
	
</head>
<body>
	<header>
		<div class="container">
			<div id="logo">
				<%= link_to image_tag('logo_mobile.png', height: '40px', id: 'logo-norm'), '/' %>
				<%= link_to image_tag('compass.png', height: '40px', id: 'logo-mob'), '/' %>
			</div>

			<nav>
				<%= render 'layouts/links' %>
				<a id="nav-trigger"><i class="fa fa-bars"></i></a>
			</nav>
		</div>
	</header>

	<nav id="slideout">
		<%= render 'layouts/links' %>
	</nav>

	<div id="nav-screen"></div>

	<%= yield %>

	<footer>
		<%= image_tag 'compass_light.png' %>
	</footer>

</body>
</html>

app/views/layouts/dash.html.erb
<%= render template: "layouts/application" %>	

<div id="dash-wrap">

	<div class="container" id="dashboard">
		
		<div id="dash-links" class="column-3">
			<div id="dash-links-top"></div>
			<ul>
				<li><%= link_to 'Analytics', '' %></li>
				<li><%= link_to 'Koinonia', '/dashboard/koinonia' %></li>
				<li><%= link_to 'Calendar', '/dashboard/calendars' %></li>
				<!-- <li><%= link_to 'Staff', '' %></li> -->
				<li><%= link_to 'Sermons', '/dashboard/sermons' %></li>
				<li><%= link_to 'Alert', '/dashboard/alert' %></li>
			</ul>
			<div id="dash-links-bottom"></div>
		</div>
		

		<section id="dash-content" class="column-9">
			<%= yield :dash %>
		</section>
	</div>
</div>

<script>
	$('footer').hide();
</script>